In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.metrics import confusion_matrix , classification_report
from sklearn.model_selection import train_test_split



In [2]:
dataset=pd.read_csv('Dataset.csv')
dataset

Unnamed: 0                                              title  \
0               0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1               1                                                NaN   
2               2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3               3  Bobby Jindal, raised Hindu, uses story of Chri...   
4               4  SATAN 2: Russia unvelis an image of its terrif...   
...           ...                                                ...   
72129       72129  Russians steal research on Trump in hack of U....   
72130       72130   WATCH: Giuliani Demands That Democrats Apolog...   
72131       72131  Migrants Refuse To Leave Train At Refugee Camp...   
72132       72132  Trump tussle gives unpopular Mexican leader mu...   
72133       72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text  label  
0      No comment is expected from Barack Obama Membe...      1  
1         Did they post their votes for Hillary already?      1  
2       Now, most of the demonstrators gathered last ...      1  
3      A dozen politically active pastors came here f...      0  
4      The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
...                                                  ...    ...  
72129  WASHINGTON (Reuters) - Hackers believed to be ...      0  
72130  You know, because in fantasyland Republicans n...      1  
72131  Migrants Refuse To Leave Train At Refugee Camp...      0  
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...      0  
72133  Goldman Sachs Endorses Hillary Clinton For Pre...      1  

[72134 rows x 4 columns]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  72134 non-null  int64 
 1   title       71576 non-null  object
 2   text        72095 non-null  object
 3   label       72134 non-null  int64 
dtypes: int64(2), object(2)
memory usage: 2.2+ MB


In [4]:
y = dataset.label
print(f'Ratio of real and fake news:')
y.value_counts(normalize=True).rename({1: 'real', 0: 'fake'})

Ratio of real and fake news:


real    0.514404
fake    0.485596
Name: label, dtype: float64

In [5]:
dataset.drop(["Unnamed: 0"], axis=1, inplace=True)


In [6]:
dataset.isnull().sum()

title    558
text      39
label      0
dtype: int64

In [7]:
dataset = dataset.fillna('')

In [8]:
dataset.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [9]:
dataset.nunique()

title    62348
text     62719
label        2
dtype: int64

In [10]:
import re
dataset['text'] = dataset['text'].map(lambda x: re.sub('[-,\.!?]', '', x))

In [11]:
dataset['text'] = dataset['text'].map(lambda x: x.lower())

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()
label = le.fit_transform(dataset['text'])
label1=le.fit_transform(dataset['title'])
dataset.drop("text", axis=1, inplace=True)
dataset.drop("title", axis=1, inplace=True)
dataset["text"] = label
dataset["title"] = label1

In [14]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [15]:
X_train,X_test,y_train,y_test=train_test_split(dataset.drop('label',axis=1),dataset['label'],test_size=0.3,random_state=101)

In [16]:
from sklearn.naive_bayes import GaussianNB
NBmodel=GaussianNB()
NBmodel.fit(X_train,y_train)





GaussianNB()

In [17]:


predicted=NBmodel.predict(X_test)
predicted



array([0, 1, 0, ..., 1, 0, 1], dtype=int64)

In [19]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
cm2=confusion_matrix(y_test,predicted)
score2=accuracy_score(y_test,predicted)
cr2=classification_report(y_test,predicted,digits=4)
auc2=roc_auc_score(y_test,predicted)

In [20]:
print('Confusion Matrix for Naive Bayes:''\n',cm2 )
print('Accuracy Score for Naive Bayes:',round(score2,4) )
print('Auc Score for Naive Bayes:',round(auc2,4) )

Confusion Matrix for Naive Bayes:
 [[7023 3471]
 [4880 6267]]
Accuracy Score for Naive Bayes: 0.6141
Auc Score for Naive Bayes: 0.6157


In [21]:
print('Classification Report for Naive Bayes:''\n''\n',cr2)

Classification Report for Naive Bayes:

               precision    recall  f1-score   support

           0     0.5900    0.6692    0.6271     10494
           1     0.6436    0.5622    0.6001     11147

    accuracy                         0.6141     21641
   macro avg     0.6168    0.6157    0.6136     21641
weighted avg     0.6176    0.6141    0.6132     21641



In [22]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split 
from sklearn import metrics 

In [23]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [24]:
cm2=confusion_matrix(y_test,y_pred)
score2=accuracy_score(y_test,y_pred)
cr2=classification_report(y_test,y_pred,digits=4)
auc2=roc_auc_score(y_test,y_pred)

In [25]:
print('Confusion Matrix for decision tree:''\n',cm2 )
print('Accuracy Score for decision tree:',round(score2,4) )
print('Auc Score for decision tree:',round(auc2,4) )

Confusion Matrix for decision tree:
 [[ 9254  1240]
 [  869 10278]]
Accuracy Score for decision tree: 0.9025
Auc Score for decision tree: 0.9019


In [26]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Classification Report for Decision Tree:""\n",cr2)



Accuracy: 0.9025460930640913
Classification Report for Decision Tree:
               precision    recall  f1-score   support

           0     0.9142    0.8818    0.8977     10494
           1     0.8923    0.9220    0.9069     11147

    accuracy                         0.9025     21641
   macro avg     0.9032    0.9019    0.9023     21641
weighted avg     0.9029    0.9025    0.9025     21641



In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, random_state = None)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10)

In [28]:
y_pred = rf.predict(X_test)

In [29]:
cm2=confusion_matrix(y_test,y_pred)
score2=accuracy_score(y_test,y_pred)
cr2=classification_report(y_test,y_pred,digits=4)
auc2=roc_auc_score(y_test,y_pred)

In [30]:
print('Confusion Matrix for random forest :''\n',cm2 )
print('Accuracy Score for random forest:',round(score2,4) )
print('Auc Score for random forest:',round(auc2,4) )

Confusion Matrix for random forest :
 [[ 9562   932]
 [  977 10170]]
Accuracy Score for random forest: 0.9118
Auc Score for random forest: 0.9118


In [31]:
print("Classification Report for Random Forest:""\n",cr2)



Classification Report for Random Forest:
               precision    recall  f1-score   support

           0     0.9073    0.9112    0.9092     10494
           1     0.9161    0.9124    0.9142     11147

    accuracy                         0.9118     21641
   macro avg     0.9117    0.9118    0.9117     21641
weighted avg     0.9118    0.9118    0.9118     21641



In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [33]:
y_pred = classifier.predict(X_test)

C:\Users\shruti\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [34]:
cm2=confusion_matrix(y_test,y_pred)
score2=accuracy_score(y_test,y_pred)
cr2=classification_report(y_test,y_pred,digits=4)
auc2=roc_auc_score(y_test,y_pred)

In [35]:
print('Confusion Matrix for KNN:''\n',cm2 )
print('Accuracy Score for KNN:',round(score2,4) )
print('Auc Score for KNN:',round(auc2,4) )

Confusion Matrix for KNN:
 [[8702 1792]
 [1325 9822]]
Accuracy Score for KNN: 0.856
Auc Score for KNN: 0.8552


In [36]:
print(classification_report(y_test, y_pred,digits=4))

              precision    recall  f1-score   support

           0     0.8679    0.8292    0.8481     10494
           1     0.8457    0.8811    0.8631     11147

    accuracy                         0.8560     21641
   macro avg     0.8568    0.8552    0.8556     21641
weighted avg     0.8564    0.8560    0.8558     21641



In [37]:
from sklearn.svm import SVC

In [38]:
svm_model = SVC()
svm_model = svm_model.fit(X_train,y_train)

In [39]:
y_pred = svm_model.predict(X_test)

In [40]:
cm2=confusion_matrix(y_test,y_pred)
score2=accuracy_score(y_test,y_pred)
cr2=classification_report(y_test,y_pred,digits=4)
auc2=roc_auc_score(y_test,y_pred)

In [41]:
print('Confusion Matrix for SVM:''\n',cm2 )
print('Accuracy Score for SVM:',round(score2,4) )
print('Auc Score for SVM:',round(auc2,4) )

Confusion Matrix for SVM:
 [[8926 1568]
 [5569 5578]]
Accuracy Score for SVM: 0.6702
Auc Score for SVM: 0.6755


In [42]:
print("Classification Report for SVM:""\n",cr2)


Classification Report for SVM:
               precision    recall  f1-score   support

           0     0.6158    0.8506    0.7144     10494
           1     0.7806    0.5004    0.6099     11147

    accuracy                         0.6702     21641
   macro avg     0.6982    0.6755    0.6621     21641
weighted avg     0.7007    0.6702    0.6605     21641

